language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "pypy"
install: python setup.py install
before_script: mysql -e 'create database mysqldb_test charset utf8;'
script: TESTDB=travis.cnf nosetests
